steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=heroku/buildpacks:18', '--path', 'samples/scala-play', '--publish', 'gcr.io/$PROJECT_ID/cloudbowl-samples-scala-play:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image=gcr.io/$PROJECT_ID/cloudbowl-samples-scala-play:$COMMIT_SHA', '--platform=managed', '--project=$PROJECT_ID', '--region=us-central1', '--allow-unauthenticated', '--memory=256Mi', 'cloudbowl-samples-scala-play']
